### PR TITLE
Jinja extension for (Single|Multiple)ObjectTemplateResponseMixin subclasses

### PR DESCRIPTION
**Pull request by sbutler**
Support for adding the Jinja template backend match extension to the result of get_template_names() for the various Django provided view classes.

### CODE REVIEW

**Comment by sbutler** [comment]
It looks like all those tests are failing because of a missing pytz install. I thought I did that right in setup.py. Did I miss something?

**Comment by sbutler** [comment]
n/m, I figured it out!

**Comment by niwibe** [comment]
Really awesome work! I'll review it tomorrow and merge it!

Thank you very much for your efforts.

**Comment by niwibe** [comment]
Would be awesome have some documentation for it!! :P

**Comment by sbutler** [comment]
If it's not one thing it's another ;)

I can update the documentation. Is there a release date you're targeting?

**Comment by niwibe** [comment]
Just do it in master branch. Thanks

**Pull request merged**
